name: update-sources
on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:
jobs:
  update-sources:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      - uses: ./.github/actions/setup-nix
        with:
          cachix-auth-token: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - id: update
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          VERSION=$(./update.ts | tail -1)
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
      - run: 'git config user.email 41898282+github-actions[bot]@users.noreply.github.com'
      - run: 'git config user.name github-actions[bot]'
      - run: 'git add -A'
      - name: Commit with version
        run: |
          if ! git diff --staged --quiet; then
            git commit -m "chore: update bun to ${{ steps.update.outputs.version }}"
          fi
      - run: 'git push -u origin main'
